### ISSUE TITLE
Failed to connect to bioconductor.org port 80

### ISSUE THREAD

**Issue by aciolfi** [Bioconductor/ExperimentHub#14] opened 2020-09-04 07:12 UTC
Hi there,

I'm trying to use the ExperimentHub package, but if I run:

`ExperimentHub() `

I receive the following error:

`Error in value[[3L]](cond) : failed to connect
  reason: Failed to connect to bioconductor.org port 80: Operation timed out
  Consider rerunning with 'localHub=TRUE'`

I don't have any other connection issues with other R packages...could you please help me to figure out what's the problem?

Here's my sessionInfo:

R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] it_IT.UTF-8/it_IT.UTF-8/it_IT.UTF-8/C/it_IT.UTF-8/it_IT.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ExperimentHub_1.12.0 AnnotationHub_2.18.0 BiocFileCache_1.10.2 dbplyr_1.4.4         BiocGenerics_0.32.0 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5                    pillar_1.4.6                  compiler_3.6.1                BiocManager_1.30.10           later_1.1.0.1                 digest_0.6.25                
 [7] bit_4.0.4                     RSQLite_2.2.0                 memoise_1.1.0                 lifecycle_0.2.0               tibble_3.0.3                  pkgconfig_2.0.3              
[13] rlang_0.4.7                   shiny_1.5.0                   DBI_1.1.0                     curl_4.3                      yaml_2.2.1                    fastmap_1.0.1                
[19] dplyr_1.0.2                   httr_1.4.2                    IRanges_2.20.2                generics_0.0.2                vctrs_0.3.4                   S4Vectors_0.24.4             
[25] rappdirs_0.3.1                stats4_3.6.1                  bit64_4.0.5                   tidyselect_1.1.0              Biobase_2.46.0                glue_1.4.2                   
[31] R6_2.4.1                      AnnotationDbi_1.48.0          purrr_0.3.4                   blob_1.2.1                    magrittr_1.5                  promises_1.1.1               
[37] ellipsis_0.3.1                htmltools_0.5.0               assertthat_0.2.1              mime_0.9                      interactiveDisplayBase_1.24.0 xtable_1.8-4                 
[43] httpuv_1.5.4                  crayon_1.3.4                  BiocVersion_3.10.1

**Comment by lshep** [comment] 2020-09-04 11:24
ExperimentHub needs internet to initially connect and download resources.  Are you on a stable internet connection?
if yes, 
Are you behind a proxy?

**Comment by aciolfi** [comment] 2020-09-04 11:50
Thank you for your answer. Yes, I have a stable internet connection...everything seems to be set up properly, when I use other R packages...Which strategy is ExperimentHub using to connect and download resources? Because I cannot reproduce the connection error with other tools (I mean, using curl or the likes)...so I cannot understand what's going wrong.

**Comment by lshep** [comment] 2020-09-04 11:59
What are your results from `curl::nslookup("experimenthub.bioconductor.org")`

**Comment by aciolfi** [comment] 2020-09-04 12:34
> curl::nslookup("experimenthub.bioconductor.org")

`[1] "52.73.93.102"`

**Comment by lshep** [comment] 2020-09-04 12:43
And are you able to view `https://experimenthub.bioconductor.org`  in a webbrowser?

**Comment by aciolfi** [comment] 2020-09-04 12:52
Yes, I am.

**Comment by lshep** [comment] 2020-09-04 13:19
Could you trying running the command `ExperimentHub()` again and show full output of results  as well as results of running `traceback()` if you get an ERROR

**Comment by aciolfi** [comment] 2020-09-04 13:25
Sure.
> ExperimentHub()
```
Error in value[[3L]](cond) : failed to connect
  reason: Failed to connect to bioconductor.org port 80: Operation timed out
  Consider rerunning with 'localHub=TRUE'
Inoltre: Warning messages:
1: `select_()` is deprecated as of dplyr 0.7.0.
Please use `select()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
2: `filter_()` is deprecated as of dplyr 0.7.0.
Please use `filter()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
```

> traceback()
```
7: stop("failed to connect", "\n  reason: ", conditionMessage(err), 
       "\n  Consider rerunning with 'localHub=TRUE'")
6: value[[3L]](cond)
5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
4: tryCatchList(expr, classes, parentenv, handlers)
3: tryCatch({
       db_date <- .restrictDateByVersion(db_path)
   }, error = function(err) {
       stop("failed to connect", "\n  reason: ", conditionMessage(err), 
           "\n  Consider rerunning with 'localHub=TRUE'")
   })
2: .Hub("ExperimentHub", hub, cache, proxy, localHub, ...)
1: ExperimentHub()

```

thank you

**Comment by lshep** [comment] 2020-09-04 14:02
Sorry. I am unable to reproduce this so I'm trying to think of solutions and possible causes.  

And you are sure you are not behind any proxy?

**Comment by aciolfi** [comment] 2020-09-04 14:12
I could ask again more details to IT guys...but if the problem were the proxy, shouldn't I get an error on internet connection?

**Comment by aciolfi** [comment] 2020-09-07 08:46
Hi Ishep, the internet settings should be ok, there is a proxy but port 80 is open...However, to test my internet settings if I set a generic proxy

```
setExperimentHubOption("PROXY", "http://proxy.dom.com")
> ExperimentHub()
Cannot determine internet connection.
 If you experience connection issues consider using 'localHub=TRUE'
Error in value[[3L]](cond) : failed to connect
  reason: Failed to connect to bioconductor.org port 80: Operation timed out
  Consider rerunning with 'localHub=TRUE'
```

I get a first error on internet connection, as I supposed...maybe there are other specific proxy settings that I could try?
thanks

**Comment by mtmorgan** [comment] 2020-09-07 13:34
Is it possible to update your R (to 4.0.2) and hence use a current version of ExperimentHub? Does

```
httr::GET("http://bioconductor.org/config.yaml")
```
work? I think you are ending up there after `.restrictDateByVersion` calls `.biocVersionDate`
```
> AnnotationHub:::.restrictDateByVersion
function (path)
{
    dates <- as.POSIXlt(.possibleDates(path), format = "%Y-%m-%d")
    restrict <- as.POSIXlt(.biocVersionDate(BiocManager::version()),
        format = "%Y-%m-%d")
```
and we have
```
> AnnotationHub:::.biocVersionDate
function (biocversion)
{
    if (length(biocversion) > 1L)
        stop("length(biocversion) must == 1")
    yaml <- httr::content(GET("http://bioconductor.org/config.yaml"),
        encoding = "UTF-8", as = "text")
```

**Comment by aciolfi** [comment] 2020-09-07 14:56
At this moment update my R is not so convenient, frankly.
However, regarding your question:

```
 httr::GET("http://bioconductor.org/config.yaml")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to bioconductor.org port 80: Operation timed out

```

The usual error...so httr::GET does't work, as you supposed.

But if I use https (if this could help):

```
httr::GET("https://bioconductor.org/config.yaml")
Response [https://bioconductor.org/config.yaml]
  Date: 2020-09-07 14:25
  Status: 200
  Content-Type: <unknown>
  Size: 7.9 kB
<BINARY BODY>
```

And it seems that I can get the yaml file:

```
> yaml <- httr::content(GET("https://bioconductor.org/config.yaml"), encoding = "UTF-8", as = "text")
> yaml
[1] "---\n## Lines that must be updated when we release a new software version are \n## indicated in comments below\n\noutput_dir: output\nstaging_deploy_root: biocadmin@staging.bioconductor.org:/loc/www/bioconductor-test.fhcrc.org\nproduction_deploy_root: webadmin@master.bioconductor.org:/extra/www/bioc\n\n## CHANGE THIS WHEN WE RELEASE A VERSION:\nrelease_version: \"3.11\"\nr_version_associated_with_release: \"4.0.0\"\nr_version_associated_with_devel: \"4.0.0\"\n\n## CHANGE THIS WHEN WE RELEASE A VERSION:\ndevel_version: \"3.12\"\n\n## CHANGE THIS WHEN WE ADD A VERSION:\n## This is the list of all versions for which we want to generate \"new\" \n## bioc-views, package index, and package detail pages.\n## if old versions (no older than 2.5) need to be rebuilt for any reason,\n## add them here, but in most cases this should just contain the\n## release and devel versions (though after a release you should\n## let the no-longer-release version build one last time so package\n## landing pages won't say \"release version\"):\nversions:\n- \"3.11\"\n- \"3.12\"\n\n## CHANGE THIS (i.e., uncomment) as various parts of the new devel version \n## become available. set to \"[]\" if none are available.\ndevel_repos:\n- \"bioc\"\n- \"data/experiment\"\n- \"workflows\"\n- \"data/annotation\"\n\n## CHANGE this when the build machines change:\n## also, don't include machines that are not building yet (comment them out)\nactive_release_builders:\n  linux: \"malbec2\"\n  windows: \"tokay2\"\n  mac_highsierra: \"machv2\"\nactive_devel_builders:\n  linux: \"malbec1\"\n  windows: \"tokay1\"\n#  mac_highsierra: \"machv2\"\n\n## CHANGE this when the single package builder builds\n## on a newer version of bioc\nsingle_package_builder:\n  bioc_version: \"3.12\"\n  r_version: \"4.0\"\n\nrss_hub_url: \"https://pubsubhubbub.appspot.com/\"\n## CHANGE these as AMI IDS change\nami_ids:\n bioc2_8: ami-3a2ef452\n bioc2_9: ami-2623f94e\n bioc2_10: ami-5621fb3e\n bioc2_11: ami-f827fd90\n bioc2_12: ami-7224fe1a\n bioc2_13: ami-4a25ff22\n bioc2_14: ami-9c25fff4\n bioc3_0: ami-be7917d6\n bioc3_1: ami-a3d126c8\n bioc3_2: ami-85d88de0\n bioc3_3: ami-abd0b3bc\n bioc3_4: ami-8946709f\n bioc3_5: ami-279a315d\n bioc3_6: ami-ac5df1d3\n bioc3_7: ami-01bcd08e357360496\n bioc3_8: ami-0565362d8bfb9cbed\n bioc3_9: ami-0f5d1990d8c571cdf\n bioc3_10: ami-0c5ab50ca03a54468\n bioc3_11: ami-02159c2acbdc8f7a9\n bioc3_12: ami-04c50efb93570d53a\nstring_pattern_type: legacy\ndata_sources:\n- items_root: /\n  layouts_root: /\n  type: filesystem_unified\n  identifier_type: legacy\n  encoding: utf-8\n  config:\n    encoding: utf-8\n- items_root: /\n  type: biostar_list\n  identifier_type: legacy\n  encoding: utf-8\n  config:\n    gmane_rss_url: 'http://rss.gmane.org/messages/excerpts/gmane.science.biology.informatics.conductor'\n    cache_file: tmp/gmane_list_cache_file.yaml\n    encoding: utf-8\n    ttl: 10\n- items_root: /help/bioc-views/package-pages\n  layouts_root: /\n  type: bioc_views\n  identifier_type: legacy\n  encoding: utf-8\n  config:\n    json_dir: \"assets/packages/json\"\n    encoding: utf-8\n- items_root: /help/publications/papers/pubmed\n  type: pubmed_papers\n  identifier_type: legacy\n  encoding: utf-8\n  config:\n    cache_file: tmp/pubmed_cache_file.yaml\n    retmax: 20\n    ttl: 24\n    baseurl: http://eutils.ncbi.nlm.nih.gov/entrez/eutils/\n#   queried database, e.g. \"pubmed\" or \"pmc\"; can be a vector\n    db: [pubmed, pmc]\n    term: bioconductor\n#   Sorting of query results. This one is database-specific; possible values include\n#   pubmed: pub+date, first+author, last+author, journal, title, relevance\n#   pmc: print+pub+date, electronic+pub+date, journal, pmc+live+date\n#   For default sorting leave this field out\n    sort: [ \"\", electronic+pub+date]\n# CHANGE THIS when it becomes apparent which future versions of BioC will\n# work with which versions of R:\nr_ver_for_bioc_ver:\n  \"1.6\": \"2.1\"\n  \"1.7\": \"2.2\"\n  \"1.8\": \"2.3\"\n  \"1.9\": \"2.4\"\n  \"2.0\": \"2.5\"\n  \"2.1\": \"2.6\"\n  \"2.2\": \"2.7\"\n  \"2.3\": \"2.8\"\n  \"2.4\": \"2.9\"\n  \"2.5\": \"2.10\"\n  \"2.6\": \"2.11\"\n  \"2.7\": \"2.12\"\n  \"2.8\": \"2.13\"\n  \"2.9\": \"2.14\"\n  \"2.10\": \"2.15\"\n  \"2.11\": \"2.15\" # R switching to yearly releases, BioC remaining the same\n  \"2.12\": \"3.0\"\n  \"2.13\": \"3.0\"\n  \"2.14\": \"3.1\"\n  \"3.0\": \"3.1\"\n  \"3.1\": \"3.2\"\n  \"3.2\": \"3.2\"\n  \"3.3\": \"3.3\"\n  \"3.4\": \"3.3\"\n  \"3.5\": \"3.4\"\n  \"3.6\": \"3.4\"\n  \"3.7\": \"3.5\"\n  \"3.8\": \"3.5\"\n  \"3.9\": \"3.6\"\n  \"3.10\": \"3.6\"\n  \"3.11\": \"4.0\"\n  \"3.12\": \"4.0\"\n# UPDATE THIS when we release a version\nrelease_dates: # old info from http://en.wikipedia.org/wiki/Bioconductor#Milestones\n  \"1.0\": \"1/5/2001\"\n  \"1.1\": \"11/19/2002\"\n  \"1.2\": \"5/29/2003\"\n  \"1.3\": \"10/30/2003\"\n  \"1.4\": \"5/17/2004\"\n  \"1.5\": \"10/25/2004\"\n  \"1.6\": \"5/18/2005\"\n  \"1.7\": \"10/14/2005\"\n  \"1.8\": \"4/27/2006\"\n  \"1.9\": \"10/4/2006\"\n  \"2.0\": \"4/26/2007\"\n  \"2.1\": \"10/8/2007\"\n  \"2.2\": \"5/1/2008\"\n  \"2.3\": \"10/22/2008\"\n  \"2.4\": \"4/21/2009\"\n  \"2.5\": \"10/28/2009\"\n  \"2.6\": \"4/23/2010\"\n  \"2.7\": \"10/18/2010\"\n  \"2.8\": \"4/14/2011\"\n  \"2.9\": \"11/1/2011\"\n  \"2.10\": \"4/2/2012\"\n  \"2.11\": \"10/3/2012\"\n  \"2.12\": \"4/4/2013\"\n  \"2.13\": \"10/15/2013\"\n  \"2.14\": \"4/14/2014\"\n  \"3.0\": \"10/14/2014\"\n  \"3.1\": \"4/17/2015\"\n  \"3.2\": \"10/14/2015\"\n  \"3.3\": \"5/4/2016\"\n  \"3.4\": \"10/18/2016\"\n  \"3.5\": \"4/25/2017\"\n  \"3.6\": \"10/31/2017\"\n  \"3.7\": \"05/01/2018\"\n  \"3.8\": \"10/31/2018\"\n  \"3.9\": \"05/03/2019\"\n  \"3.10\": \"10/30/2019\"\n  \"3.11\": \"04/28/2020\"\nmirrors:\n - 0-Bioconductor:\n   - institution: Bioconductor, automatic redirection to servers worldwide\n     institution_url: http://bioconductor.org\n     contact: Bioconductor Maintainer\n     contact_email: maintainer@bioconductor.org\n     city: World-wide\n     mirror_url: http://bioconductor.org/\n     https_mirror_url: https://bioconductor.org/\n     rsync: secure_mirror_from_master\n     country_code: us\n - Germany:\n   - institution: Department of Statistics, TU Dortmund\n     institution_url: http://www.statistik.tu-dortmund.de/\n     contact: Uwe Ligges\n     contact_email: ligges@statistik.tu-dortmund.de\n     mirror_url: http://bioconductor.statistik.tu-dortmund.de/\n     https_mirror_url: https://bioconductor.statistik.tu-dortmund.de/\n     rsync: \n     city: Dortmund\n     country_code: de\n - Japan:\n   - institution: The Institute of Statistical Mathematics\n     institution_url: http://www.ism.ac.jp/\n     contact: Keisuke Honda\n     contact_email: khonda@ism.ac.jp\n     mirror_url: http://bioc.ism.ac.jp/\n     https_mirror_url: https://bioc.ism.ac.jp/\n     rsync: secure_mirror_from_master\n     country_code: jp\n     city: Tachikawa\n   - institution: RIKEN Advanced Center for Computing and Communication\n     institution_url: http://accc.riken.jp/en/\n     contact: Itoshi NIKAIDO, Ph.D.\n     contact_email: dritoshi@gmail.com\n     mirror_url: http://bioconductor.riken.jp/\n     https_mirror_url: https://bioconductor.riken.jp/\n     rsync: secure_mirror_from_master\n     country_code: jp\n     city: Wako\n - China:\n   - institution: TUNA Mirror Site, Tsinghua University \n     institution_url: mirrors.tuna.tsinghua.edu.cn\n     contact: Miao Wang \n     contact_email: mirroradmin@tuna.tsinghua.edu.cn \n     mirror_url: http://mirrors.tuna.tsinghua.edu.cn/bioconductor/\n     https_mirror_url: https://mirrors.tuna.tsinghua.edu.cn/bioconductor/ \n     rsync: secure_mirror_from_master\n     country_code: cn \n     city: Peking \n - Germany2:\n   - institution: GWDG\n     institution_url: https://ftp.gwdg.de/\n     contact: Tim Ehlers and Steffen Klemer\n     contact_email: ftpmaster@gwdg.de\n     mirror_url: https://ftp.gwdg.de/pub/misc/bioconductor/\n     https_mirror_url: https://ftp.gwdg.de/pub/misc/bioconductor/\n     rsync: secure_mirror_from_master\n     city: Gottingen\n     country_code: de\n - China2:\n   - institution: eScience Center, Nanjing University\n     institution_url: https://sci.nju.edu.cn/\n     contact: Ge Yao\n     contact_email: yaoge@nju.edu.cn\n     mirror_url: https://mirrors.nju.edu.cn/bioconductor/\n     https_mirror_url: https://mirrors.nju.edu.cn/bioconductor/\n     rsync: secure_mirror_from_master\n     city: Nanjing\n     country_code: cn\n"
```

Do you think it could be possible to find out a workaround?

**Comment by mtmorgan** [comment] 2020-09-07 15:11
The version of ExperimentHub / AnnotationHub available to your version of R is no longer being updated, so there is no way to produce an updated version. You could download AnnotationHub from https://github.com/Bioconductor/AnnotationHub/archive/RELEASE_3_10.zip, edit the line in R/Hub-utils.R to point to https://.../config.yaml, then install `install.packages("path/to/AnnotationHub", repos = NULL, type = "source")`

**Comment by aciolfi** [comment] 2020-09-07 15:19
OK, thank you very much for your help. Hopefully in the next weeks we'll also update our R version.

**Comment by aciolfi** [comment] 2020-09-07 15:34
Yes,  http://bioconductor.org/config.yaml is available via web browser.

Thanks

**Comment by lshep** [comment] 2020-09-08 14:57
Since we cannot update older versions and this was corrected in the most recent versions I am closing this issue.

**Closed by lshep** 2020-09-08 14:57 UTC
